### ISSUE TITLE
Compile Kotlin test Windows doesn't works

### ISSUE THREAD

**Issue by Gashmob** [Gashmob/Logger#2]
The batch script : 
```batch
:: Compile tests
kotlinc -cp Logger_Kotlin.jar test\main.kt test\BasicTest1.kt test\Test.kt test\ThreadTest1.kt test\ThreadTest2.kt test\utils.kt -include-runtime

:: Run tests
kotlin -cp Logger_Kotlin.jar; MainKt
```
doesn't works in the github workflow :
```yaml
test-windows:
  runs-on: windows-latest
  defaults:
    run:
      working-directory: Kotlin
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3

   - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@main

    - name: Run test
      run: .\test\run.bat
```

See run https://github.com/Gashmob/Logger/runs/7520749347?check_suite_focus=true
